# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Metadata-DB
version:      1.12
version_from: lib/Metadata/DB.pm
installdirs:  site
requires:
    Cwd:                           0
    DBD::mysql:                    0
    DBD::SQLite:                   0
    File::Copy:                    2
    HTML::Entities:                0
    HTML::Template::Default:       1.04
    LEOCHARRE::Class2:             1.03
    LEOCHARRE::Database:           1
    LEOCHARRE::DEBUG:              0
    Metadata::Base:                0
    Smart::Comments:               0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
